image:
  file: .gitpod.Dockerfile
checkoutLocation: '.'
vscode:
  extensions:
    - ms-python.python@v2024.12.3
    - ms-python.debugpy
    - samuelcolvin.jinjahtml
    #- innoverio.vscode-dbt-power-user@0.44.7
