
version: 2

models:
  - name: customer
    description: "Our customers"
    columns:
      - name: c_custkey
        description: "The primary key for this table"
        data_tests:
          - unique
          - not_null
      - name: c_nationkey
        description: "They key of the nation of this customer"
        data_tests:
          - not_null
          - relationships:
              to: ref("nation")
              field: "n_nationkey"
  - name: nation
    description: "The nations where our company operates"
    columns:
      - name: n_nationkey
        description: "The primary key for this table"
        data_tests:
          - unique
          - not_null
  - name: nation_stats
    description: "Customer stats for each nation where our company operates"
    columns:
      - name: n_nationkey
        description: "The nationkey of this nation"
        data_tests:
          - unique
          - not_null
          - relationships:
              to: ref("nation")
              field: "n_nationkey"
      - name: nation
        description: "The name of the nation"
        data_tests:
          - unique
          - not_null
      - name: min_balance
        description: "The minimum balance of customers in this nation"
        data_tests:
          - not_null
      - name: max_balance
        description: "The maximum balance of customers in this nation"
        data_tests:
          - not_null
      - name: avg_balance
        description: "The average balance of customers in this nation"
        data_tests:
          - not_null

sources:
- name: tpch
  database: snowflake_sample_data
  schema: tpch_sf1
  tables:
  - name: customer
  - name: nation
